# Generated by Django 3.0.4 on 2020-03-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0003_auto_20200326_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='preview_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
